name: Python Lint Code Scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  security-events: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pylint

      - name: Run Python Lint Code Scanning
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
